version: '3'

services:
  postgres-db:
    build: 
      context: /
      dockerfile: Dockerfile_db
    ports:
      - "5432:5432"

  flask-app:
    build: 
      context: /
      dockerfile: Dockerfile
    ports:
      - "8080:8080"